### ISSUE TITLE
Why it is so delicate>

### ISSUE THREAD

**Issue by neoxharsh** [pimoroni/hyperpixel#14]
The screen is so delicate, I do not understand why? there are many screens out their but none are as delicate as this. I would like to suggest Pimoroni to consider this issue, as Raspberry PI is a development board, and it means that, it will be used a bit roughly. and taking the hat on and off will be frequent. I bought the hat last week and now it has started having dead pixels and the touch screen also do not work, always go to the bottom of the screen

**Comment by Gadgetoid** [comment]
The HyperPixel screen is just so darned nice- being as it is the same resolution of the official Pi Touchscreen but much, much daintier. It's unfortunate that it's not the hardiest of displays, but it's shiny enough that there's no sense letting that get in the way of making it available.

There are, indeed, many other screens, but getting hold of one the right size, resolution, availability, price, interface and the many other factors that whittle down the number of considerations is really, really, thoroughly difficult. More so than you'd imagine!

If you're having trouble with yours, you should bung us an email to support@pimoroni.com.
