### ISSUE TITLE
Can't install drivers

### ISSUE THREAD

**Issue by Matte93** [pimoroni/hyperpixel#17]
Updating apt indexes...
.....................W: Failed to fetch http://dl.bintray.com/pipplware/dists/jessie/main/binary/./Packages  403  Forbidden [IP: 5.153.35.248 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
Apt failed to update indexes!
pi@retropie:~/hyperpixel $

**Comment by Gadgetoid** [comment]
You need to update RetroPie, it's installed a broken/deprecated repository on your system:

https://retropie.org.uk/forum/topic/12205/403-forbidden-when-updating
