### ISSUE TITLE
Larger console font

### ISSUE THREAD

**Issue by snobu** [pimoroni/hyperpixel#18]
Is there a way to embiggen the (framebuffer) console font?

/etc/defaults/console-setup:

```
FONTFACE="Terminus"
FONTSIZE="32x16"
```

32 is max supported by Linux for the console.. so i guess i need to lower the HyperPixel resolution. How would i do that? Can i scale to something like 640x200, is there a scaler built into the display?

I just need very large fonts for a demo, i would never ruin the super high res in normal conditions as it looks sharp as a knife. I can't run X, although that would make it easy.

Maybe a different framebuffer terminal could pull this off?

**Comment by Gadgetoid** [comment]
I'm not sure! Perhaps fbterm would help?

It would be tricky to adjust the scale- since anything that's not a 1:1 or 2:1 ratio would distort to the point of illegibility you're left with just: 800x480 or 400x240, although you might find the latter usable, I don't know how you would accomplish this on HyperPixel since it just accepts raw DPI signals from the Pi and can't do any scaling of its own.

You could, perhaps, experiment with setting:
```
framebuffer_width=400
framebuffer_height=240
```

**Comment by snobu** [comment]
Looks like framebuffer settings just paint a smaller area of the display, there's no scaling. I gave up and installed minimal Xorg and xterm.

Sharing the xterm command line for _large enough font to see from 3m (that's 10ft across the pond) with good eye sight_, should someone in the future work their way into a similar situation (who am i kidding, i'm trying to get this out there so i can find my post again in the future).

```bash
xterm -geometry 39x11 -rv -cr cyan -bd black \
      -fa 'Inconsolata' -fs 32 \
      -e '/app/start.sh'

# -fs is font size
# -e is execute this
# -fa is monospace font name
# -rv is reverse colors (black on white by default in xterm)
# -cr is cursor color
# -bd is xterm border color
# -geometry is like trig but easier :)
```
![pi](https://user-images.githubusercontent.com/6472374/33216455-97fe8092-d13c-11e7-914a-9619c595a9d4.jpg)

Touchscreen just works in xterm which is very cool to highlight text by touch. I could probably make it scroll instead with a little effort..

I'm sure `fbterm` would also be a solution - they claim to support freetype2 fonts, not sure what didn't work for me but it really pissed me off (looks like i already blocked that memory).

Anyway @Gadgetoid thanks for looking at this one! HyperPixel is fantastic, every time people see it on that Pi they ask if it's Full HD and i say yes :)
