### ISSUE TITLE
Would it work the same on Ausus TinkerBoard with armbian ?

### ISSUE THREAD

**Issue by VladoPortos** [pimoroni/hyperpixel#24]
Would the install files work in armbian with asus tinker board, gpio should be the same, but not sure what else might be needed...

**Comment by Gadgetoid** [comment]
I very much doubt it- I can't find any information to confirm or deny if the TinkerBoard supports DPI, but I suspect not.

**Comment by VladoPortos** [comment]
You are right, I could not get it to work... I used spare rpi3 that one works great.
