### ISSUE TITLE
redirecting console to /dev/fb0 ?

### ISSUE THREAD

**Issue by VladoPortos** [pimoroni/hyperpixel#25]
Is there a way to redirect console to dev/fb0 ? most LCDs are on /dev/fb1 and there is program, to mirror the fb0 to fb1...  mostly I'm curious how could I mirror remote ssh connection to the hyperpixel...

**Comment by Gadgetoid** [comment]
Are you running Raspbian with Pixel Desktop and seeing a desktop environment on HyperPixel?

You would have to use some sort of terminal multiplexer, like `screen` to set up a shared session that you then attach to via SSH.

This could be accomplished by creating an entering a screen session upon boot- you'd need to first ensure that you're not running X which you can turn off with `raspi-config`.

Then at the bottom of your `~/.profile` file you might get away with adding this monstrosity:

```
# Connect to an existing screen session "shared_session" or create it
if [ ! "`screen -list | grep shared_session`" == "" ]; then
    screen -x shared_session
else
    screen -S shared_session
fi
```

Now in theory your Pi will boot up to command-line showing the screen session `shared_session` and any connection you make over SSH will also show that same session, mirroring everything you type.
