### ISSUE TITLE
What is the power consumption of the hyperpixel?

### ISSUE THREAD

**Issue by smlehbleh** [pimoroni/hyperpixel#27]
Hello,
I'm about to buy the hyperpixel, but I wanted to check what kind of power I'll need for it. What is the power consumption in milliamps or watts?

**Comment by sandyjmacdonald** [comment]
At full brightness the backlight consumes 110mA, and the rest about 30mA.

**Comment by nadaso8** [comment]
Really it's that low?! I guess I just thought screens in general had a higher current draw.
