### ISSUE TITLE
Enable easy switch between hyperpixel and HDMI

### ISSUE THREAD

**Issue by hoegge** [pimoroni/hyperpixel#32]
It would be very useful if there was an easy way to disable the display (i.e. enable HDMI again) and enable (when done using HDMI) like a script so you do not have to uninstall every time you need to change display. Would that be easy to do?

Thanks

**Comment by Gadgetoid** [comment]
There's a good topic about this on our forums, here: https://forums.pimoroni.com/t/hyperpixel-selective-output-eg-on-boot/5193

**Comment by hoegge** [comment]
Is there any way to use the HDMI as main display and then only use the HyperPixel for dedicated programs? The hyperpixel display is not very suitable for debugging and developing.

**Comment by tinspin** [comment]
TLDR on the link above is: If you write a 1 to this file /sys/class/backlight/rpi_backlight/bl_power the screen turns off... write a 0 again to turn it on... and this works in realtime! Compared to DPI, HDMI/DVI is just bad! I wish we could get larger DPI screens...
Edit; FYI this means you can turn the screen on/off from the keyboard with ZERO latency!
Prediction: GPIO is the everything connector/cable of the future if we can handle the electromagnetics! NOT USB!
Going even further RxTx (also known as COMM and RS232) is better than I2C and SPI!
