### ISSUE TITLE
superfine stripes across display

### ISSUE THREAD

**Issue by lutzha** [pimoroni/hyperpixel#38]
hello,

dont get me wrong, this display is amazing for raspberry. but i dont know if my problems is just as designed or a problem.

the screen has almost non visible super light stripes horizontally. its only recogniceable, if u know it or in camera preview its more visible.

is this normal?

**Comment by Gadgetoid** [comment]
Do they align with the metal contacts along the far right edge? You might be seeing the electrodes of the touch digitiser which I'm guessing can't be totally invisible.

**Comment by lutzha** [comment]
hmmm... size of silver dots matches, but i am not sure. is it normal then, to see only horizontally stripes?  if i play with clk frequency they are more visible. is there no possibility to set clk frequency in recommended range of the display (max 30mhz) ?

**Comment by Counterdoc** [comment]
I see them too btw...

**Comment by lutzha** [comment]
![img_20180711_175142](https://user-images.githubusercontent.com/5307846/42584815-5927fb62-8534-11e8-98c5-c16aa9334f05.jpg)

in camera preview its mostly visible

**Comment by Gadgetoid** [comment]
Closing since this issue has gone stale.
