### ISSUE TITLE
Does Manual Install Actually Work?

### ISSUE THREAD

**Issue by drewcovi** [pimoroni/hyperpixel#39]
I'm attempting to get hyperpixel working on Raspberry Pi with only the config.txt and overlays.

According to the readme I should only need to:
- Enable Legacy GL driver
- Copy/Paste config.txt variables
- Ensure overlays are present

I don't need to hotplug the display... but doing the above led to a dark display with no response.

**Comment by Gadgetoid** [comment]
Actually in *all* cases `hyperpixel-init` is required. The instructions aren't very clear on that point. The display will basically do nothing until it's initialised.
