### ISSUE TITLE
[Solved] Screen blank using setup.sh from this repo

### ISSUE THREAD

**Issue by omiq** [pimoroni/hyperpixel#40]
* Latest Raspbian Stretch
* Pi Zero W
* apt-get Updated, Upgraded, firmware updated

The Curl command responds with ```We can't connect to the Internet, check your network!"``` which is weird because the curl is using the internet to get the script.

Cloning this repo gets further but on reboot the screen flashes then goes blank.

```hyperpixel-init``` flashes the screen then goes blank

The backlight is on

### Solved

* Install Jesse
* The curl command still does not work on Jesse but ran it anyway
* git clone https://github.com/pimoroni/hyperpixel/
* run the new install.sh after chmod +x

**Comment by Gadgetoid** [comment]
IIRC our curl scripts check for connectivity by pinging a known-more-or-less-stable IP address. This may be something you've got blocked. In hindsight it may be completely unecessary since- as you rightfully point out- curl had to connect to the internet to get the script in the first place.
