### ISSUE TITLE
Touch not working on Pi 3B+ with Buster

### ISSUE THREAD

**Issue by gazzmanzx6** [pimoroni/hyperpixel#50]
Having just updated my Pi 3B+ to the latest Buster build the touch screen has stopped working. It was fine before.
I have tried reinstalling the drivers but touch still doesn't work.

` hyperpixel-touch.service - Hyperpixel LCD Touch Screen Driver Daemon
   Loaded: loaded (/usr/lib/systemd/system/hyperpixel-touch.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-10-02 15:53:07 BST; 6s ago
  Process: 1167 ExecStart=/usr/bin/hyperpixel-touch (code=exited, status=0/SUCCESS)
 Main PID: 1179 (code=exited, status=1/FAILURE)

Oct 02 15:53:07 raspberrypi systemd[1]: hyperpixel-touch.service: Service RestartSec=100ms expired, sche
Oct 02 15:53:07 raspberrypi systemd[1]: hyperpixel-touch.service: Scheduled restart job, restart counter
Oct 02 15:53:07 raspberrypi systemd[1]: Stopped Hyperpixel LCD Touch Screen Driver Daemon.
Oct 02 15:53:07 raspberrypi systemd[1]: hyperpixel-touch.service: Start request repeated too quickly.
Oct 02 15:53:07 raspberrypi systemd[1]: hyperpixel-touch.service: Failed with result 'exit-code'.
Oct 02 15:53:07 raspberrypi systemd[1]: Failed to start Hyperpixel LCD Touch Screen Driver Daemon.`

**Comment by gazzmanzx6** [comment]
It appears this is to do with the latest kernel. It also affects the Pi 2B as well.
Rolling back to 4.19.118 makes the touch work again.
`sudo rpi-update e1050e94821a70b2e4c72b318d6c6c968552e9a2`

**Comment by Gadgetoid** [comment]
Might be worth trying the Pi 4 branch of this GitHub repository. I'm not sure if the fixes I had to make there translate across but it's highly likely.

One gotcha between major kernel releases is that the pre-compiled `dtbo` files might no longer be compatible. I've changed the "pi4" branch here to compile them from source, instead.

**Comment by gazzmanzx6** [comment]
Didn't work at first but running hyperpixel-init seems to have fixed it.
Thanks.

**Comment by Gadgetoid** [comment]
> Didn't work at first but running hyperpixel-init seems to have fixed it.

ugh I need to figure out why the at-boot `hyperpixel-init` isn't working. But glad this got you up and running most of the way.
