### ISSUE TITLE
Use Hyperpixel 4 square together with serial GPS module (UART)

### ISSUE THREAD

**Issue by 8lue5ky** [pimoroni/hyperpixel#55]
Hi

I know that the Hyperpixel display uses most of the GPIO pins. But is there a way to use the display together with a serial GPS module?

Thank you.

**Comment by Gadgetoid** [comment]
You could try a USB to UART adaptor, I've never attempted it with something like an external GPS but it's your only real option.

Hyperpixel uses *all* of the GPIO - https://pinout.xyz/pinout/hyperpixel
