### ISSUE TITLE
Install script assumes Python is already installed

### ISSUE THREAD

**Issue by ngreatorex** [pimoroni/hyperpixel#7]
I don't use the standard Raspbian full image, but instead a custom debootstrapped minimal image. As such, I don't already have Python installed. The install script should either fail if python2.7 isn't installed or instead automatically install it.

**Comment by Gadgetoid** [comment]
Install scripts are ostensibly for only Raspbian - although they do support Raspbian-based distributions and some other OSes. We'll look into this, but can't support every corner case. It's assumed if you know what you're doing enough to bootstrap a system without Python then you're probably comfortable picking and choosing the components you want from the manual setup.

**Comment by ngreatorex** [comment]
That's a fair point, but I still think there should be a guard to stop it leaving your system in a broken state. I will look at putting together a PR this evening to fix it.

**Comment by RogueM** [comment]
I am fixing this... however, the setup already installs python packages that depend on a minimal python system, so if this fails currently then I think the issue is more complex than described.

**Comment by ngreatorex** [comment]
@RogueM 

The issue was that the "dpkg -i" call for python-evdev leaves the system in a broken state (as dpkg doesn't handle dependencies), so all the subsequent "apt-get install" calls fail to install anything and just complain. 

The python-evdev deb you provide has "Depends: libc6 (>= 2.4), python (>= 2.7), python (<< 2.8)". As it depends on python and not python-minimal, the change you committed won't quite fix it. The python package is simply there for dependencies, so installing python rather than python-minimal uses only a few bytes more (it's not python-all).

**Comment by RogueM** [comment]
ah, Ok... I blame @Gadgetoid who made the edev package a while back... I doubt that it needs more than python-minimal but we'll look into. Ultimately there is no point trying to support a system where python is absent but then install everything but the kitchen sink ;-)

**Comment by ngreatorex** [comment]
@RogueM the python package is the correct dependency. It's a more or less empty package that itself depends on python-minimal. The "'kitchen sink" package, python-all, is separate.

**Comment by RogueM** [comment]
well, like I said initially, your problem is more complex than described. The `python` package is in the recommends list for `python-minimal` so it should really be pulled in automatically. But I can change that, and make it explicit, sure.
